
"""
Client for Human Behaviour Analysis API

This script performs the following operations:

1. Loads a video file from disk.
2. Extracts frames at a configurable time interval.
3. Encodes the extracted frames as Base64 strings.
4. Sends the frames to a FastAPI server for analysis.
5. Receives and displays the behaviour description generated by
   the Vision Language Model (Qwen2.5-VL).

Requirements:
    - OpenCV
    - Requests

Usage:
    python client.py
"""

import cv2
import base64
import requests

# ============================================================
# Configuration
# ============================================================

# Path to the input video file
VIDEO_PATH = "test.mp4"

# Public API endpoint exposed through ngrok
SERVER_URL = "include your ngrok server url"

# Extract one frame every N seconds
FRAME_INTERVAL_SECONDS = 1

# Maximum number of frames to send to the server
MAX_FRAMES = 8


# ============================================================
# Frame Extraction
# ============================================================

def extract_frames(
    video_path: str,
    interval_seconds: int = 1,
    max_frames: int = 8
):
    """
    Extract frames from a video at a fixed time interval.

    Parameters
    ----------
    video_path : str
        Path to the input video.

    interval_seconds : int
        Number of seconds between extracted frames.

    max_frames : int
        Maximum number of frames to extract.

    Returns
    -------
    list[str]
        List of Base64 encoded image frames.
    """

    frames = []

    cap = cv2.VideoCapture(video_path)

    fps = cap.get(cv2.CAP_PROP_FPS)

    if fps <= 0:
        raise ValueError(
            "Could not determine video FPS."
        )

    frame_interval = int(
        fps * interval_seconds
    )

    frame_count = 0

    while True:

        success, frame = cap.read()

        if not success:
            break

        if frame_count % frame_interval == 0:

            # Convert frame to JPEG
            _, buffer = cv2.imencode(
                ".jpg",
                frame
            )

            # Encode image as Base64 string
            encoded_frame = base64.b64encode(
                buffer.tobytes()
            ).decode("utf-8")

            frames.append(encoded_frame)

            # Stop when maximum frame count is reached
            if len(frames) >= max_frames:
                break

        frame_count += 1

    cap.release()

    return frames


# ============================================================
# API Communication
# ============================================================

def analyze_video(video_path: str):
    """
    Extract frames from a video and send them to the server
    for behaviour analysis.

    Parameters
    ----------
    video_path : str
        Path to the input video.

    Returns
    -------
    dict | str
        JSON response from the server or raw text response.
    """

    frames = extract_frames(
        video_path=video_path,
        interval_seconds=FRAME_INTERVAL_SECONDS,
        max_frames=MAX_FRAMES
    )

    print(
        f"Extracted {len(frames)} frames "
        f"from '{video_path}'."
    )

    payload = {
        "frames": frames
    }

    response = requests.post(
        SERVER_URL,
        json=payload,
        timeout=300
    )

    print(
        f"Server Response Code: "
        f"{response.status_code}"
    )

    try:
        return response.json()
    except Exception:
        return response.text


# ============================================================
# Entry Point
# ============================================================

if __name__ == "__main__":

    print(
        "Starting Human Behaviour Analysis..."
    )

    result = analyze_video(VIDEO_PATH)

    print("\n========== RESPONSE ==========\n")

    print(result)

